export const dealerData = [
  {
    name: "Green Grocers",
    logo: "MarketLogo.jpg",
    since: "2018",
    location: "San Francisco",
    rate: 4.9,
    sales: "2.5k",
    saved: "98",
    categories: ["Vegetables", "Fruits"],
    borderColor: "border-t-green-500",
  },
  {
    name: "City Bakery",
    logo: "MarketLogo.jpg",
    since: "2015",
    location: "New York",
    rate: 4.7,
    sales: "1.2k",
    saved: "95",
    categories: ["Bread", "Pastries"],
    borderColor: "border-t-orange-500",
  },
  {
    name: "Organic Hub",
    logo: "MarketLogo.jpg",
    since: "2020",
    location: "Austin",
    rate: 4.8,
    sales: "3.8k",
    saved: "99",
    categories: ["Organic", "Dairy"],
    borderColor: "border-t-blue-500",
  },
];
