export const categories = [
  "All Deals",
  "Fruits & Veg",
  "Bakery",
  "Dairy & Eggs",
  "Meat & Seafood",
  "Pantry",
  "Beverages",
];

export const featuredDeals = [
  {
    image: "Organic.jpg",
    discount: "50%",
    timeLeft: "2 days",
    shopName: "Whole Foods Market",
    title: "Organic Vegetable Bundle Box",
    rate: 4,
    reviews: 120,
    currentPrice: "10.00",
    oldPrice: "20.00",
  },
  {
    image: "Pain.jpg",
    discount: "50%",
    timeLeft: "2 days",
    shopName: "Whole Foods Market",
    title: "Organic Vegetable Bundle Box",
    rate: 4,
    reviews: 120,
    currentPrice: "10.00",
    oldPrice: "20.00",
  },
  {
    image: "Organic.jpg",
    discount: "50%",
    timeLeft: "2 days",
    shopName: "Whole Foods Market",
    title: "Organic Vegetable Bundle Box",
    rate: 4,
    reviews: 120,
    currentPrice: "10.00",
    oldPrice: "20.00",
  },
  {
    image: "Pain.jpg",
    discount: "50%",
    timeLeft: "2 days",
    shopName: "Whole Foods Market",
    title: "Organic Vegetable Bundle Box",
    rate: 4,
    reviews: 120,
    currentPrice: "10.00",
    oldPrice: "20.00",
  },
];
